fs=2000;
dt=1/fs;
T=5;
t=0:dt:T;
u=@(z) double(z>=0);
w=u(t)-u(t-5);
h=sin(3*pi*t).*w;
x=cos(2*pi*t).*w;
y=conv(h,x,'full')*dt;
ty=0:dt:(2*T);
figure('color','w');
subplot(3,1,1);
plot(t,x,'LineWidth',1.5);
grid on ;
xlabel('t(s)');
ylabel('h(t)');
title('4554 7373');
subplot(3,1,2);
plot(t, h, 'LineWidth', 1.5);
grid on; xlabel('t (s)'); ylabel('h(t)');
title('Impulse response h(t) = sin(3\pi t)[u(t)-u(t-5)]');
subplot(3,1,3);
plot(ty, y, 'LineWidth', 1.6);
grid on; xlabel('t (s)'); ylabel('y(t)');
title('Output y(t) = (h * x)(t) via numerical convolution');
